<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitdadb5063d509b7135480e451b2391a67
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'SquareConnect\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'SquareConnect\\' => 
        array (
            0 => __DIR__ . '/..' . '/square/connect/lib',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitdadb5063d509b7135480e451b2391a67::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitdadb5063d509b7135480e451b2391a67::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
