<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Helpdesk3
 * @version    3.3.10
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php /** @var AW_Helpdesk3_Block_Customer_Ticket_View_Escalate $this */?>
<div class="awhdu3-customer-escalate-ticket-form panel panel--from-bottom">
    <div class="panel__inner">
        <div class="panel__header">
            <button class="panel__back panel__action"><svg class="panel__action-icon panel__action-icon panel__action-icon--back svg-icon"><use xlink:href="#icon-arrow-back" /></svg><span class="hide"><?php echo $this->__("Back") ?></span></button>
            <h2 class="panel__title"><span class="panel__title-text"><?php echo $this->__('Ticket Escalation') ?></span></h2>
            <button class="panel__close panel__action"><svg class="panel__action-icon panel__action-icon--close svg-icon"><use xlink:href="#icon-close" /></svg><span class="hide"><?php echo $this->__("Close") ?></span></button>
        </div><!-- .panel__header -->

        <div class="panel__content">
            <div id="awhdu3-ticket-view-escalate-textarea">
                <h2><?php echo $this->__('Are you dissatisfied with the quality of support?');?></h2>
                <form method="post" id="awhdu3-ticket-view-escalate-form" action="<?php echo $this->getEscalatePostAction();?>">
                    <p class="form__field form__field--required">
                        <label for="awhdu3-ticket-view-escalate-form-textarea" class="form__label form__label--required"><?php echo $this->__('Please, provide us information why are you not satisfied with quality of support.');?></label>
                        <textarea class="required-entry" id="awhdu3-ticket-view-escalate-form-textarea" name="content"></textarea>
                    </p>
                    <p class="form__submit-wrapper">
                        <p class="form__required-hint">
                            <?php echo $this->__('Required Fields') ?>
                        </p>
                        <div id="awhdu3-ticket-view-escalate-textarea-bottom-group">
                            <button id="awhdu3-ticket-view-escalate-textarea-btn-escalate" title="<?php echo $this->__('Escalate') ?>" class="button"><span><span><?php echo $this->__('Escalate') ?></span></span></button>
                        </div>
                    </p>
                </form>
            </div>
            <script type="text/javascript">
                (function(){
                    var postBtn = $('awhdu3-ticket-view-escalate-textarea-btn-escalate');
                    var form = new VarienForm('awhdu3-ticket-view-escalate-form');
                    if (!postBtn || !form) {
                        return;
                    }

                    postBtn.observe('click', function(e){
                        form.submit();
                    });
                })();
            </script>
        </div>
    </div>
</div>