<?php
/**
 * Created by PhpStorm.
 * User: DEV5
 * Date: 04.10.2017
 * Time: 16:29
 */
class BroSolutions_ShipmentCommentGrid_Adminhtml_ShipmentcommentgridController extends Mage_Adminhtml_Controller_Action
{
    public function _isAllowed()
    {
        return true; // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {
        $params = $this->getRequest()->getParams();
        $order = Mage::getModel('sales/order')->load($params['id']);
        $order->setShipsFrom($params['ships_from']);
        try {
            $order->save();
            $answer = '\'Ships from\' was saved successfully';
        } catch (Exception $e) {
            Mage::logException($e);
            $answer = '\'Ships from\' wasn\'t saved';
        }
        $arr = array(
            'answer' => $answer,
        );

        $this->getResponse()->setBody(
            json_encode($answer));
    }
}
