
<?php
$catalogSearchHelper =  $this->helper('catalogsearch');
?>

<form id="search_mini_form" class="input-group" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
        <input id="search" type="search" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>" class="form-control input-text required-entry" maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>" placeholder="<?php echo $this->quoteEscape($this->__('Search by keyword/item #')) ?>" />
        <span class="input-group-btn">
            <button type="submit" title="<?php echo $this->quoteEscape($this->__('Search')) ?>" class="button search-button btn btn-default"><i class="fa fa-search" aria-hidden="true"></i></button>
            </button>
        </span>
    <div id="search_autocomplete" class="search-autocomplete"></div>
    <script type="text/javascript">
        //<![CDATA[
        var searchForm = new Varien.searchForm('search_mini_form', 'search', '');
        searchForm.initAutocomplete('<?php echo $catalogSearchHelper->getSuggestUrl() ?>', 'search_autocomplete');
        //]]>
    </script>
</form>