<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Helpdesk3
 * @version    3.3.10
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
    $panelName = "awhdu3-customer-create-ticket-form";
?>
<p class="awhdu3__create-ticket">
    <button type="submit" id="aw_hdu_ticket_create_form_link" title="<?php echo $this->__('Create New Ticket');?>" class="button js-open-panel" data-open-panel="<?php echo $panelName ?>"><?php echo $this->__('Create New Ticket');?></button>
</p><!-- .form__submit-wrapper -->
<script type="text/javascript">
    document.observe('dom:loaded', function () {
        if ($$('.<?php echo $panelName ?>')) {
            var rafInvite = new awMobile3.panel('<?php echo $panelName ?>');
        }
    });

</script>