<script type="text/javascript">
    var paymentForm = new SqPaymentForm({
        applicationId: '<?php echo $this->getApplicationId(); ?>',
        inputClass: 'sq-input',
        inputStyles: [
            {
                fontSize: '13px',
                padding: '10px 5px 2px'
            }
        ],
        cardNumber: {
            elementId: 'sq-card-number',
            placeholder: '•••• •••• •••• ••••'
        },
        cvv: {
            elementId: 'sq-cvv',
            placeholder: 'CVV'
        },
        expirationDate: {
            elementId: 'sq-expiration-date',
            placeholder: 'MM/YY'
        },
        postalCode: {
            elementId: 'sq-postal-code'
        },
        callbacks: {

            // Called when the SqPaymentForm completes a request to generate a card
            // nonce, even if the request failed because of an error.
            cardNonceResponseReceived: function(errors, nonce, cardData) {
                if (errors) {
                    console.log("Encountered errors:");

                    // This logs all errors encountered during nonce generation to the
                    // Javascript console.
                    errors.forEach(function(error) {
                        console.log('  ' + error.message);
                    });

                    // No errors occurred. Extract the card nonce.
                } else {
                    jQuery('#square-payment-nonce-id').val(nonce);
                    jQuery('#square-payment-nonce-id').attr('disabled', false);
                    payment.save();
                    // Delete this line and uncomment the lines below when you're ready
                    // to start submitting nonces to your server.


                    /*
                     These lines assign the generated card nonce to a hidden input
                     field, then submit that field to your server.
                     Uncomment them when you're ready to test out submitting nonces.

                     You'll also need to set the action attribute of the form element
                     at the bottom of this sample, to correspond to the URL you want to
                     submit the nonce to.
                     */
                    // document.getElementById('card-nonce').value = nonce;
                    // document.getElementById('nonce-form').submit();

                }
            },

            unsupportedBrowserDetected: function() {
                // Fill in this callback to alert buyers when their browser is not supported.
            },

            // Fill in these cases to respond to various events that can occur while a
            // buyer is using the payment form.
            inputEventReceived: function(inputEvent) {
                switch (inputEvent.eventType) {
                    case 'focusClassAdded':
                        // Handle as desired
                        break;
                    case 'focusClassRemoved':
                        // Handle as desired
                        break;
                    case 'errorClassAdded':
                        // Handle as desired
                        break;
                    case 'errorClassRemoved':
                        // Handle as desired
                        break;
                    case 'cardBrandChanged':
                        // Handle as desired
                        break;
                    case 'postalCodeChanged':
                        // Handle as desired
                        break;
                }
            }
        }
    });

    paymentForm.build();
	if(jQuery('.onepage-payment-radio').length == 0 && jQuery('#square-payment-form-wrapper').length > 0){
		jQuery('#square-payment-form-wrapper').show();
	}
	
    window.requestCardNonce = function() {

        paymentForm.requestCardNonce();
    }


    function showQuarePaymentForm(event)
    {
		var elementId = event.target.id;
        if(elementId == 'p_method_squarepayment'){
            jQuery('#square-payment-form-wrapper').show();

        } else {
            jQuery('#square-payment-form-wrapper').hide();
        }
    }
    jQuery('.onepage-payment-radio').click(function(event){
        showQuarePaymentForm(event);
    });
    jQuery('.onepage-payment-radio').each(function(key, value){
        if(jQuery(value).is(':checked')){
            var elementId = value.id;
            if(elementId == 'p_method_squarepayment'){
                jQuery('#square-payment-form-wrapper').show();

            } else {
                jQuery('#square-payment-form-wrapper').hide();
            }
        }
    });
</script>
<style type="text/css">
    .sq-input {
        display: block;
        width: 100%;
        height: 34px;
        padding: 6px 12px;
        font-size: 14px;
        line-height: 1.42857143;
        color: #555;
        background-color: #fff;
        background-image: none;
        border: 1px solid #ccc;
        border-radius: 4px;
        -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        -webkit-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        -o-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s
    }
    .sq-input--focus {
        outline-width: 5px;
        outline-color: #70ACE9;
        outline-offset: -1px;
        outline-style: auto;
    }
    .sq-input--error {
        outline-width: 5px;
        outline-color: #FF9393;
        outline-offset: 0px;
        outline-style: auto;
    }

    .square-form label {
        margin-top: 5px;
        margin-bottom: 2px;
    } 
</style>
<div id="square-payment-form-wrapper" style="display:none;">
<h2><?php echo $this->getMethodTitle(); ?></h2>
<form id="square-form" class="square-form" novalidate action="/process-card.php" method="post">
    <label>Card Number</label>
    <div id="sq-card-number"></div>
    <label>CVV</label>
    <div id="sq-cvv"></div>
    <label>Expiration Date</label>
    <div id="sq-expiration-date"></div>
    <label>Postal Code</label>
    <div id="sq-postal-code"></div>
    <input type="hidden" id="card-nonce" name="nonce">

</form>

<div id="errors"></div>
    <input id="square-payment-nonce-id" type="hidden" name="payment[square-payment-nonce]">
</div>
